---
title: "Presentations"
---

Whenever possible we make presentations available at the [Presentations](/presentations.html) page.

We now stream our meetups through Zoom, RSVP on our [meetup page](https://www.meetup.com/nyhackr/). You can find past meetup recordings on [YouTube](https://www.youtube.com/playlist?list=PLlzRFZmxVl9QqpFSfkv6JdYrg29xFwxRt&utm_source=nyhackr). They are also listed on the [Presentations page](/presentations.html).

```{r setup,include=FALSE}
knitr::opts_chunk$set(cache=FALSE,echo=FALSE)
```

```{r common-actions,include=FALSE}
source("utils/utils.r")
```

```{r layout,dependson=c('common-actions')}
crosstalk::bscols(widths=c(2, 10), device='md',
       list(
           topicFilter,
           presenterFilter,
           venueFilter,
           nameFilter,
           titleFilter,
           videoFilter
       ),
       list(
           # talks table
           makeDatatable(talks_shared, 
                         colsToHide=c('ShareKey'), 
                         scrollX=FALSE, width='100%', scrollY=200, height=200,
                         order=list(list(1, 'desc')),
                         elementID='PresentationsTable',
                         scrollCollapse=FALSE
                         # colsToFixWidth='Presentation', columnsWidth='100px'
           ),
           htmltools::tags$p(class='spacer'),
           # meetup table
           makeDatatable(events_shared, class='display cell-border',
                         colsToHide=c('ShareKey'),
                         colsToFixWidth=c('Date', 'Description', 'Meetup', 'Speakers', 'Video'), columnsWidth='35px',
                         scrollX=FALSE, width='100%', scrollY=400, height=400,
                         order=list(list(0, 'desc')),
                         elementID='EventsTable'
           )
       )
)
```
