---
title: "DT Test"
author: "Jared P. Lander"
date: "February 19, 2017"
output: html_document
---

```{r,echo=FALSE}
theDf <- data.frame(
    ID=c('a', 'b', 'c', 'a'), 
    Name=c('Jared', 'Bob', 'Sarah', 'Danny'), 
    Number=c(1, 3, 5, 7),
    stringsAsFactors=FALSE)
```

```{r, eval=FALSE,echo=FALSE}
library(DT)
datatable(theDf[, , drop=FALSE], rownames=FALSE, elementId='jpl',
          options = list(
              initComplete = JS(
                  "function () {",
                  "var api = this.api();",
                  "api.$('td').click( function () {",
                  "api.search( this.innerHTML ).draw();",
                  "} );",
                  "}"
              )
          ))
```

<table border="0" cellspacing="5" cellpadding="5">
        <tbody><tr>
            <td>Minimum number:</td>
            <td><input type="text" id="min" name="min"></td>
        </tr>
        <tr>
            <td>Maximum number:</td>
            <td><input type="text" id="max" name="max"></td>
        </tr>
    </tbody></table>

```{r,echo=FALSE}
library(DT)
datatable(theDf[, , drop=FALSE], rownames=FALSE, elementId='jpl',
          options = list(
              initComplete = JS(
                  "function (settings, json) {",
                  "var api = this.api();",
                  "var table = $('#jpl table').DataTable();",
                  "var dude = table.column(0).data().unique()[0];",
                  "var filtered = table.column(2).data().filter(function(value, index){ return value < 5 ? true: false;});",
                  # "var dude = table.column(0).data().unique();",
                  # "table.row(filtered[1]).remove().draw();",
                  # "api.search(dude).draw();",
                  # "alert('hi ' + ' bye');",
                  "}"
              )
          ))
```


```{r}
library(crosstalk)
shareDF <- SharedData$new(theDf)
filted <- filter_select(id='SimpleFilter', label='Choose one', sharedData=shareDF, group=~ID)
filted$children
```

