---
title: "Presentations"
---

```{r setup,include=FALSE}
knitr::opts_chunk$set(cache=TRUE,echo=FALSE)
```

```{r common-actions,include=FALSE,cache=TRUE}
1-9
source("utils.R")
```

```{r layout,dependson=c('common-actions')}
shiny::fluidRow(
    shinydashboard::box(width=2,
        topicFilter,
        speakerFilter,
        presenterFilter,
        venueFilter,
        nameFilter,
        titleFilter
        ),
    shinydashboard::box(
        width=10,
        shiny::fluidRow(
            shinydashboard::box(
                width=12, 
                makeDatatable(talks_shared, 
                              colsToHide='ShareKey',
                              scrollX=TRUE, width='100%',
                              elementID='PresentationsTable')
            )
        ),
        shiny::fluidRow(
            shinydashboard::box(
                width=12, collapsible=TRUE,#collapsed=TRUE, 
                makeDatatable(events_shared, class='display cell-border',
                              colsToHide=c('ShareKey', 'Date'),
                              # colsToFixWidth='Description', columnsWidth='100px',
                              scrollX=TRUE, width='100%',
                              elementID='EventsTable')
            )
        )
    )
)

# bscols(widths=c(2, 10), device='md',
#        list(
#            topicFilter,
#            speakerFilter,
#            presenterFilter,
#            venueFilter,
#            nameFilter,
#            titleFilter),
#        list(
#        makeDatatable(events_shared, class='display cell-border',
#                      colsToHide=c('ShareKey', 'Date'),
#                      # colsToFixWidth='Description', columnsWidth='100px',
#                      scrollX=TRUE, width='100%', 
#                      elementID='EventsTable'),
#        makeDatatable(talks_shared, 
#                      colsToHide='ShareKey', 
#                      scrollX=TRUE, width='100%', 
#                      elementID='PresentationsTable', height=100)
#        )
# )
```

